import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const electron = createRequire(import.meta.url)('electron');
const env = { ...process.env, LUX_NODE_EXECUTABLE: process.execPath, LUX_WORKSPACE: root };
if (process.argv.includes('--smoke')) env.LUX_STUDIO_SMOKE = '1';
delete env.ELECTRON_RUN_AS_NODE;
const child = spawn(electron, [resolve(root, 'apps/studio/dist/main.cjs')], { cwd: root, env, stdio: 'inherit', windowsHide: false });
child.on('error', error => { console.error(error); process.exitCode = 1; });
child.on('exit', code => { process.exitCode = code ?? 1; });
